name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Windows 10 SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22621
      - name: Install Python 3.7.9 x86
        uses: actions/setup-python@v5
        with:
          python-version: '3.7.9'
          architecture: x86
      - name: Install Python 3.7.9 x64
        uses: actions/setup-python@v5
        with:
          python-version: '3.7.9'
          architecture: x64
      - name: Install Python 3.11.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'
      - name: Run build script
        run: |
          python build.py --github-actions
      - name: Release LunaTranslator
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/LunaTranslator_x86.zip
            build/LunaTranslator.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
